name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: popovv2
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker image from Docker Hub
      run: docker pull docker.io/popovv2/coucou_studi:latest

    - name: Login to Heroku Container Registry
      run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

    - name: Tag the Docker image
      run: docker tag docker.io/popovv2/coucou_studi:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Push to Heroku Container Registry
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release the image to Heroku
      run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

    - name: Clean up
      if: always()
      run: docker image rm popovv2/coucou_studi:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
