name: Docker Hello Studi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd ./Python && docker build . --file dockerfile --tag coucou_studi:$(date +%s)
