name: Docker Hello Studi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: popovv2
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push Docker image
      run: |
        cd ./Python
        docker build . --file dockerfile --tag coucou_studi:lastest
        docker push popovv2/coucou_studi:lastest
